name: pull
on: pull_request
jobs:
  wait_for_vercel:
    name: Wait for vercel
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120

  tests:
    name: End-to-end tests is another repo
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/github-status-action
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: saisiddulugari/cypress-e2e-tests
          event-type: my-event
          client-payload: '${{ needs.wait_for_vercel.outputs.preview_url }}", "sha": "${{ github.sha }}"}'


