name: pull
on: pull_request
jobs:
  wait_for_vercel:
    name: Wait for vercel
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
    - name: Waiting for 200 from the Vercel Preview
      uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
      id: waitFor200
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        max_timeout: 60
        
    - run: echo ${{steps.waitFor200.outputs.url}}

  tests:
    name: End-to-end tests is another repo
    needs: wait_for_vercel
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/github-status-action
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: saisiddulugari/cypress-e2e-tests
          event-type: my-event
          client-payload: '{"sai": "${{ needs.wait_for_vercel.outputs.preview_url }}", "sha": "${{ github.sha }}"}'



