name: pull
on: pull_request
jobs:
  set-status:
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/marketplace/actions/github-status-action
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: saisiddulugari/cypress-e2e-tests
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
